---
title: "BEE 4750 Homework 5: Solid Waste Disposal"
format:
    html:        
        warning: true
        error: true
    ipynb:
        warning: true
        error: true
        code-annotation: below
engine: julia
julia:
    exeflags: ["+1.10.4"]
format-links: []
---

::: {.content-visible when-format="ipynb"}
**Name**:

**ID**:
:::

::: {.callout-important icon=false}
### Due Date

Friday, 10/27/23, 9:00pm
:::

::: {.content-visible when-format="html"}

:::{.callout-caution}

If you are enrolled in the course, make sure that you use the GitHub Classroom link provided in Ed Discussion, or you may not be able to get help if you run into problems.

Otherwise, you can [find the Github repository here]({{< var github_org.repo >}}/hw04).

:::

:::

## Overview

::: {.cell .markdown}

### Instructions

- In Problem 1, you will formulate, solve, and analyze a standard generating capacity expansion problem.
- In Problem 2, you will add a CO~2~ constraint to the capacity expansion problem and identify changes in the resulting solution.

:::

::: {.cell .markdown}

### Load Environment

The following code loads the environment and makes sure all needed packages are installed. This should be at the start of most Julia scripts.

```{julia}
#| output: false
import Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()
```

```{julia}
using JuMP
using HiGHS
using DataFrames
using GraphRecipes
using Plots
using Measures
using MarkdownTables
```

:::

::: {.cell .markdown}

## Background

Three cities are developing a coordinated municipal solid waste (MSW) disposal plan.  Three disposal alternatives are being considered: a landfill (LF), a materials recycling facility (MRF), and a waste-to-energy facility (WTE). The capacities of these facilities and the fees for operation and disposal are provided in the table below.

| **Disposal Facility** | **Capacity** (Mg/d) | **Fixed cost** (\$/d) | **Tipping Fee ** (\$/Mg) | **Recycling Cost** (\$/Mg) |
|:-------------:|:------------:|:-------------:|:---------:|:--------------:|
| Landfill 					| 200 | 2000 | 50 |					   |
| Materials Recycling Facility 		| 350 | 1500 | 7  | 40 (per Mg recycled)|
| Waste-to-Energy Facility  | 210 | 2500 | 60 |					   |

Transportation costs are \$1.5/Mg-km, and the relative distances between the cities and facilities are provided in the table below. 

| **City/Facility**  |  **Landfill (km)** | **MRF (km)**  | **WTE (km)** |
|:-------------:|:------------:|:-------------:|:-------------:|
| 1  	  | 5  | 30 | 15 |
| 2 	  | 15 | 25 | 10 |
| 3       | 13 | 45 | 20 |
| LF	  | - | 32  | 18 |
| MRF	  | 32 | - | 15 |
| WTE	  |  18 | 15 | -  |

The fixed costs associated with the disposal options are incurred only if the particular disposal option is implemented.  The three cities produce 100, 90, and 120 Mg/day of solid waste, respectively, with the composition provided in the table below. 

| **Component**  | **% of total mass**  | **Combustion ash** (%) | **MRF Recycling rate** (%) |
|:-------------------:|:------------:|:-------------:|:-------------:|
| Food Wastes  	  	  | 15  | 8   | 0   |
| Paper & Cardboard	  | 40  | 7   | 55  |
| Plastics	  		  | 5   | 5   | 15  |
| Textiles	   		  | 3   | 10  | 10  |
| Rubber, Leather	  | 2   | 15  | 0   |
| Wood		  		  | 5   | 2   | 30  |
| Yard Wastes	  	  | 18  | 2   | 40  |
| Glass	  			  | 4   | 100 | 60  |
| Ferrous	  		  | 2   | 100 | 75  |
| Aluminum	  		  | 2   | 100 | 80  |
| Other Metal	  	  | 1   | 100 | 50  |
| Miscellaneous	  	  | 3   | 70  | 0   |

The information in the above table will help you determine the overall recycling and ash fractions. Note that the recycling residuals, which may be sent to either landfill or the WTE, have different ash content than the ash content of the original MSW. You will need to determine these fractions to construct your mass balance constraints. 

**Reminder**: Use `round(x; digits=n)` to report values to the appropriate precision!

:::


## Problems (Total: 40 Points)

::: {.cell .markdown}

### Problem 1 (22 points)

In this problem, you will develop an optimal disposal plan for the two cities.

:::

::: {.cell .markdown}

#### Problem 1.1 (3 points)

Based on the information above, calculate the overall recycling and ash fractions for the waste produced by each city.

:::

::: {.cell .markdown}

#### Problem 1.2 (2 points)

What are the decision variables for your optimization problem? Provide notation and variable meaning.

:::

::: {.cell .markdown}

#### Problem 1.3 (3 points)

Formulate the objective function. Make sure to include any needed derivations or justifications for your equation(s).

:::

::: {.cell .markdown}

#### Problem 1.4 (4 points)

Derive all relevant constraints. Make sure to include any needed justifications or derivations. 

:::

::: {.cell .markdown}

#### Problem 1.5 (3 points)

Implement your optimization problem in `JuMP`.

:::

::: {.cell .markdown}

#### Problem 1.6 (2 points)

Find the optimal solution. Report the optimal objective value. 

:::

::: {.cell .markdown}

#### Problem 1.7 (5 points)

Draw a diagram showing the flows of waste between the cities and the facilities.  Which facilities (if any) will not be used? Does this solution make sense?

:::

::: {.cell .markdown}

### Problem 2 (18 points)

It is projected that in the near future the state will introduce a carbon tax that will increase the cost for transportation and for disposal by incineration. It is estimated that the additional costs will be:

* tipping fee for the WTE facility will increase to\$75/Mg; and
* transportation costs will increase to \$2/Mg-km. 

In this context, the cities are considering adding another landfill and want to know if this would be cost-effective compared to using the current facilities with the carbon tax. This landfill would have a maximum capacity of 100 Mg/day and would be located with the following distances from the existing sites (excluding LF1):

| **City/Facility**  | **Distance to LF2 (km)**
|:-------------:|:------------:|
| 1  	  | 45  |
| 2 	  | 35 | 
| 3       | 15 |
| MRF	  | 35  | 
| WTE	  | 50 | 

The fixed cost of operating this facility would be the same as the first landfill, but the tipping cost would be increased to \$60/Mg-day.

:::

::: {.cell .markdown}

#### Problem 2.1 (5 points)

What changes are needed to your optimization program from Problem 1 for this decision problem? Formulate any different variables, objectives, and/or constraints.

:::

::: {.cell .markdown}

#### Problem 2.2 (3 points)

Implement the new optimization problem in `JuMP`. 

:::

::: {.cell .markdown}

#### Problem 2.3 (5 points)

Find the optimal solution and report the optimal objective value. Provide a diagram showing the new waste flows. 

:::

::: {.cell .markdown}

#### Problem 2.4 (5 points)

Would you recommend that the cities build the new landfill? Why or why not? Your answer should be based on your analysis but can draw on other considerations as appropriate or desired.

:::

::: {.cell .markdown}
## References

List any external references consulted, including classmates.
:::